{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - watch
- apiGroups:
  - config.operator.kube-stager.io
  resources:
  - mongoconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.operator.kube-stager.io
  resources:
  - mysqlconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.operator.kube-stager.io
  resources:
  - redisconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.operator.kube-stager.io
  resources:
  - serviceconfigs
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - job.operator.kube-stager.io
  resources:
  - backups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - job.operator.kube-stager.io
  resources:
  - backups/finalizers
  verbs:
  - update
- apiGroups:
  - job.operator.kube-stager.io
  resources:
  - backups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - job.operator.kube-stager.io
  resources:
  - dbinitjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - job.operator.kube-stager.io
  resources:
  - dbinitjobs/finalizers
  verbs:
  - update
- apiGroups:
  - job.operator.kube-stager.io
  resources:
  - dbinitjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - job.operator.kube-stager.io
  resources:
  - dbmigrationjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - job.operator.kube-stager.io
  resources:
  - dbmigrationjobs/finalizers
  verbs:
  - update
- apiGroups:
  - job.operator.kube-stager.io
  resources:
  - dbmigrationjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - site.operator.kube-stager.io
  resources:
  - stagingsites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - site.operator.kube-stager.io
  resources:
  - stagingsites/finalizers
  verbs:
  - update
- apiGroups:
  - site.operator.kube-stager.io
  resources:
  - stagingsites/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - task.operator.kube-stager.io
  resources:
  - mongodatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - task.operator.kube-stager.io
  resources:
  - mongodatabases/finalizers
  verbs:
  - update
- apiGroups:
  - task.operator.kube-stager.io
  resources:
  - mongodatabases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - task.operator.kube-stager.io
  resources:
  - mysqldatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - task.operator.kube-stager.io
  resources:
  - mysqldatabases/finalizers
  verbs:
  - update
- apiGroups:
  - task.operator.kube-stager.io
  resources:
  - mysqldatabases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - task.operator.kube-stager.io
  resources:
  - redisdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - task.operator.kube-stager.io
  resources:
  - redisdatabases/finalizers
  verbs:
  - update
- apiGroups:
  - task.operator.kube-stager.io
  resources:
  - redisdatabases/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
{{ end }}
