apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-manager-config
  namespace: {{ .Release.Namespace }}
data:
  controller_manager_config.yaml: |-
{{ toYaml .Values.config | indent 4 }}
