apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Release.Name }}-serving-cert
  name: {{ .Release.Name }}-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ .Release.Name }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-site-operator-kube-stager-io-v1-stagingsite
  failurePolicy: Fail
  name: mstagingsite.kb.io
  rules:
  - apiGroups:
    - site.operator.kube-stager.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - stagingsites
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ .Release.Name }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-site-operator-kube-stager-io-v1-stagingsite-advanced
  failurePolicy: Fail
  name: stagingsite-handler.operator.kube-stager.io
  rules:
  - apiGroups:
    - site.operator.kube-stager.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - stagingsites
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ .Release.Name }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-job-operator-kube-stager-io-v1-backup-advanced
  failurePolicy: Fail
  name: backup-handler.operator.kube-stager.io
  rules:
  - apiGroups:
    - job.operator.kube-stager.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backups
  sideEffects: None
