{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml .Values.rbac.serviceAccount.labels | indent 4 }}
  annotations:
{{ toYaml .Values.rbac.serviceAccount.annotations | indent 4 }}
{{ end }}
