apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
{{- range $key, $value := .Values.service.labels }}
    {{ $key }}: {{ $value }}
{{- end }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  name: {{ .Release.Name }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
