apiVersion: v1
name: prometheus-static-target
version: 1.0.0-rc2
appVersion: 1.0.0-rc2
description: "Prometheus static target operator to extend the functionality of Prometheus Operator"
home: https://github.com/szeber/kube-stager-prometheus-static-target
sources:
- https://github.com/szeber/kube-stager-prometheus-static-target
maintainers:
- name: Zsolt Szeberenyi
